# docker-compose.yml 


services:
  # üöÄ SOLO tu aplicaci√≥n Spring Boot
  app:
    build: .  # ‚ö° Construye usando el Dockerfile
    container_name: library_api
    ports:
      - "${PORT:-8080}:8080"  # üåê Tu API en puerto 8080
    environment:
      # üîó Render proveer√° DATABASE_URL autom√°ticamente
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d4aeea2dbo4c73ca9u8g-a.oregon-postgres.render.com:5432/library_db_zcze
      SPRING_DATASOURCE_USERNAME: biblioteca_user
      SPRING_DATASOURCE_PASSWORD: r1jZDO8WZ2NR5P0FD6L1GFwb0is0GtfQ
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      
